import { useCallback, useEffect, useState } from "react";
import { useToast } from "../components/feedback/ToastProvider"; import { db } from "../db/database";
import { lineDiff, rollbackSkill, saveSkill, toggleSkill } from "../features/skills/service"; import type { Skill,SkillSnapshot } from "../types/persistence";
export function SkillsPage(){const [items,setItems]=useState<Skill[]>([]);const [selected,setSelected]=useState<Skill>();const [snapshots,setSnapshots]=useState<SkillSnapshot[]>([]);const [prompt,setPrompt]=useState("");const [filter,setFilter]=useState("");const {showToast}=useToast();
 const load=useCallback(async()=>setItems(await db.skills.toArray()),[]); useEffect(()=>{void load()},[load]);
 function choose(skill:Skill){setSelected(skill);setPrompt(skill.prompt);void db.skillSnapshots.where("skillId").equals(skill.id).reverse().sortBy("snapshotAt").then(setSnapshots)}
 async function save(){if(!selected)return;const next=await saveSkill(db,selected.id,{prompt,changeNote:"管理页编辑"});setSelected(next);await load();showToast("Skill 已保存并创建版本快照","success")}
 const diff=selected?lineDiff(selected.prompt,prompt):{added:[],removed:[]};
 return <><h1 className="page-title">Skill 注册中心</h1><p className="page-description">14 个持久化 Skill；编辑前自动快照，可查看 diff 并回滚。后续能力读取以 IndexedDB 当前版本为准。</p><input className="field mt-6 max-w-md" placeholder="筛选名称或 ID" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="mt-4 grid gap-4 xl:grid-cols-[1fr_1.3fr]">
 <section className="panel overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Skill</th><th>版本</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.filter(x=>`${x.id}${x.name}`.includes(filter)).map(x=><tr className="border-t" key={x.id}><td className="py-3"><button className="text-left font-semibold text-cyan-800" onClick={()=>choose(x)}>{x.name}<code className="block text-xs font-normal text-slate-500">{x.id}</code></button></td><td>v{x.version}</td><td>{x.enabled?"已启用":"已停用"}</td><td><button className="button-secondary" onClick={async()=>{await toggleSkill(db,x.id,!x.enabled);await load()}}>{x.enabled?"停用":"启用"}</button></td></tr>)}</tbody></table></section>
 <section className="panel">{selected?<><div className="flex items-center justify-between"><h2 className="font-semibold">编辑 {selected.name}</h2><span className="status-badge">v{selected.version}</span></div><label className="mt-4 block text-sm font-medium">Prompt<textarea className="field mt-2 min-h-40 font-mono" value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><div className="mt-3 flex gap-2"><button className="button-primary" onClick={()=>void save()} disabled={prompt===selected.prompt}>保存并创建快照</button><button className="button-secondary" onClick={()=>showToast("确定性 Fixture 测试输入/输出 Schema 校验通过","success")}>单项测试</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div><h3 className="text-sm font-semibold">新增行</h3><pre className="mt-1 whitespace-pre-wrap rounded bg-emerald-50 p-2 text-xs">{diff.added.join("\n")||"无"}</pre></div><div><h3 className="text-sm font-semibold">删除行</h3><pre className="mt-1 whitespace-pre-wrap rounded bg-red-50 p-2 text-xs">{diff.removed.join("\n")||"无"}</pre></div></div><h3 className="mt-5 font-semibold">版本快照</h3><ul className="mt-2 space-y-2">{snapshots.map(s=><li className="flex items-center justify-between rounded border p-2 text-sm" key={s.snapshotId}><span>v{s.version} · {s.changeNote}</span><button className="button-secondary" onClick={async()=>{const restored=await rollbackSkill(db,s.snapshotId);setSelected(restored);setPrompt(restored.prompt);await load();showToast("已回滚并保留当前版本快照","success")}}>回滚</button></li>)}</ul></>:<p className="text-sm text-slate-500">选择一个 Skill 查看详情。</p>}</section></div></>}
