import type { OnboardOpsDatabase } from "../../db/database"; import type { RunRecord, UserContext } from "../../types/persistence"; import { executePlan } from "../executor/executor"; import { createPlan } from "../planner/planner"; import { validatePlan } from "../planner/validator";
export interface RunAgentInput {question:string;userContext:UserContext;conversationHistory?:string[];conversationId?:string;source?:"workspace"|"chat"}
export async function runAgent(database:OnboardOpsDatabase,input:RunAgentInput):Promise<RunRecord>{
 const started=performance.now(); const [skills,tools,knowledge,employee,agent,planner]=await Promise.all([database.skills.toArray(),database.tools.toArray(),database.knowledgeDocuments.toArray(),input.userContext.employeeId?database.employees.get(input.userContext.employeeId):undefined,database.agents.get("onboarding-agent"),database.plannerConfigs.get("default-planner")]);
 const activeSkills=skills.filter(x=>!agent||agent.skillIds.includes(x.id)); const activeTools=tools.filter(x=>!agent||agent.toolIds.includes(x.id));
 const plan=createPlan({userInput:input.question,conversationHistory:input.conversationHistory??[],userContext:input.userContext,employee,availableSkills:activeSkills,availableTools:activeTools,availableKnowledge:knowledge,mandatoryCapabilities:planner?.mandatoryCapabilities??["privacy-risk-check"]}); const validation=validatePlan(plan,activeSkills,activeTools,input.userContext);
 const executed=validation.valid?await executePlan(database,plan,input.userContext):{steps:[],evidence:[],riskResult:{decision:"block" as const,flags:validation.errors.map(x=>x.code),message:"计划校验失败，已阻断执行。"},finalReply:plan.riskFlags.length?"抱歉，我不能提供完整敏感信息或查询其他员工资料。如需协助，请联系 HR 人工核验。":plan.missingInformation.length?"请提供您的员工编号（EMP-YYYY-NNNN），完成身份确认后我才能查询个人状态。":"执行计划未通过安全校验，未调用业务能力。请补充身份信息或联系人工。",status:"error" as const};
 const now=new Date().toISOString(); const run:RunRecord={id:`RUN-${crypto.randomUUID()}`,question:input.question,conversationId:input.conversationId??`CONV-${input.userContext.employeeId??"anonymous"}`,userContextSnapshot:structuredClone(input.userContext),source:input.source??"workspace",createdAt:now,status:executed.status,finalReply:executed.finalReply,plan,planValidation:validation,steps:executed.steps,evidence:executed.evidence,riskResult:executed.riskResult,durationMs:Math.round(performance.now()-started),...(validation.valid?{}:{error:{code:"INVALID_PLAN",message:validation.errors.map(x=>x.message).join("；")}}),provider:"fixture",model:"deterministic-rules",agentVersion:`${agent?.version??3}.0.0`,plannerVersion:`rules-${planner?.version??3}.0.0`,skillVersions:Object.fromEntries(activeSkills.map(x=>[x.id,x.version])),toolVersions:Object.fromEntries(activeTools.map(x=>[x.id,x.version])),knowledgeVersions:Object.fromEntries(knowledge.map(x=>[x.id,x.version]))}; await database.runs.add(run); return run;
}
