import type { OnboardOpsDatabase } from "../../db/database";
import { runAgent } from "../../core/agent/runAgent";
import type { AgentConfig,BadCase,ConfigKind,HumanAnnotation,ImprovementDraft,PlannerConfig,RootCause,RunRecord } from "../../types/persistence";
export const diffText=(before:string,after:string)=>({removed:before.split("\n").filter(x=>!after.split("\n").includes(x)),added:after.split("\n").filter(x=>!before.split("\n").includes(x))});
export async function saveConfig(db:OnboardOpsDatabase,kind:ConfigKind,config:AgentConfig|PlannerConfig,reason="编辑保存"){const table=kind==="agent"?db.agents:db.plannerConfigs;const old=await table.get(config.id) as AgentConfig|PlannerConfig|undefined;if(old)await db.configSnapshots.add({id:`SNAP-${crypto.randomUUID()}`,kind,configId:old.id,version:old.version,content:JSON.stringify(old),createdAt:new Date().toISOString(),reason});const next={...config,version:(old?.version??0)+1,updatedAt:new Date().toISOString()};await table.put(next as never);return next}
export async function rollbackConfig(db:OnboardOpsDatabase,snapshotId:string){const snap=await db.configSnapshots.get(snapshotId);if(!snap)throw new Error("快照不存在");return saveConfig(db,snap.kind,JSON.parse(snap.content),`回滚自 v${snap.version}`)}
export async function annotateRun(db:OnboardOpsDatabase,runId:string,input:Omit<HumanAnnotation,"id"|"runId"|"createdAt"|"updatedAt">){const old=await db.humanAnnotations.where("runId").equals(runId).first(),now=new Date().toISOString();const row={...input,id:old?.id??`ANN-${crypto.randomUUID()}`,runId,createdAt:old?.createdAt??now,updatedAt:now};await db.humanAnnotations.put(row);return row}
export async function rateRun(db:OnboardOpsDatabase,runId:string,score:number,note:string){const row={id:`RATING-${crypto.randomUUID()}`,runId,score,note,createdAt:new Date().toISOString()};await db.userRatings.add(row);return row}
export async function createBadCase(db:OnboardOpsDatabase,runId:string,rootCause:RootCause,note:string):Promise<BadCase>{const now=new Date().toISOString(),row:BadCase={id:`BAD-${crypto.randomUUID()}`,runId,rootCause,status:"open",note,pendingEval:true,createdAt:now,updatedAt:now};await db.badCases.add(row);return row}
export async function createDraft(db:OnboardOpsDatabase,runId:string,targetKind:ConfigKind,targetId:string,suggestion:string,after:string):Promise<ImprovementDraft>{const target=targetKind==="agent"?await db.agents.get(targetId):await db.plannerConfigs.get(targetId);if(!target)throw new Error("改进目标不存在");const row:ImprovementDraft={id:`DRAFT-${crypto.randomUUID()}`,runId,targetKind,targetId,suggestion,before:JSON.stringify(target,null,2),after,status:"draft",createdAt:new Date().toISOString()};await db.improvementDrafts.add(row);return row}
export async function applyDraft(db:OnboardOpsDatabase,id:string){const draft=await db.improvementDrafts.get(id);if(!draft||draft.status!=="draft")throw new Error("草案不可应用");await saveConfig(db,draft.targetKind,JSON.parse(draft.after),`应用改进草案 ${id}`);const snapshot=await db.configSnapshots.where("[kind+configId]").equals([draft.targetKind,draft.targetId]).last();await db.improvementDrafts.update(id,{status:"applied",appliedAt:new Date().toISOString(),snapshotId:snapshot?.id});return db.improvementDrafts.get(id)}
export async function rerunFromBadCase(db:OnboardOpsDatabase,draftId:string){const draft=await db.improvementDrafts.get(draftId);if(!draft||draft.status!=="applied")throw new Error("请先确认并应用草案");const original=await db.runs.get(draft.runId);if(!original)throw new Error("原 Run 不存在");const rerun=await runAgent(db,{question:original.question,userContext:original.userContextSnapshot,conversationId:original.conversationId,source:original.source});await db.improvementDrafts.update(draftId,{rerunId:rerun.id});return{before:original,after:rerun}}
export interface OpsMetrics{total:number;technicalSuccessRate:number|null;qualityPassRate:number|null;averageDurationMs:number|null;handoffRate:number|null;failedSteps:Record<string,number>;riskDistribution:Record<string,number>}
export function calculateMetrics(runs:RunRecord[],annotations:HumanAnnotation[]):OpsMetrics{const judged=annotations.filter(x=>x.overall>0);return{total:runs.length,technicalSuccessRate:runs.length?runs.filter(x=>x.status==="success").length/runs.length:null,qualityPassRate:judged.length?judged.filter(x=>x.overall>=4).length/judged.length:null,averageDurationMs:runs.length?runs.reduce((n,x)=>n+x.durationMs,0)/runs.length:null,handoffRate:runs.length?runs.filter(x=>x.riskResult.decision==="handoff"||x.plan.shouldHandoff).length/runs.length:null,failedSteps:runs.flatMap(x=>x.steps).filter(x=>x.status!=="success").reduce<Record<string,number>>((a,x)=>(a[x.capabilityId]=(a[x.capabilityId]??0)+1,a),{}),riskDistribution:runs.flatMap(x=>x.riskResult.flags.length?x.riskResult.flags:["none"]).reduce<Record<string,number>>((a,x)=>(a[x]=(a[x]??0)+1,a),{})}}
